### ISSUE TITLE
Reorganize Zookeeper

### ISSUE THREAD

**Issue by vernonm** [appsoma/ansible-appsoma-mesos#4]
Install zookeepercli along with zookeeper server
Add simple command alias to allow easier command issues.

**Comment by kdemarest** [comment]
Here is the alias that worked for me:

alias zk="zookeepercli -servers $ZK_HOST_LIST -c"

sadly, under SOME circumstances you need to use

zookeepercli -servers $ZK_HOST_LIST -force -c

so using an alias is imperfect. I eventually gave up and just used zkCli,
so you can kill this task if you want to.


*Ken Demarest*
*CEO, Appsoma *
ken@appsoma.com
415.342.9731
Austin, Texas ▪ United States
